export const SET_SELECTED = 'SET_SELECTED';
export const SET_SHIFT_DOWN = 'SET_SHIFT_DOWN';
export const ON_HOVERABLE_MOUSE_ENTER = 'ON_HOVERABLE_MOUSE_ENTER';
export const ON_HOVERABLE_MOUSE_LEAVE = 'ON_HOVERABLE_MOUSE_LEAVE';