export const SET_SHIFT_DOWN = 'SET_SHIFT_DOWN';
export const ON_HOVERABLE_MOUSE_ENTER = 'ON_HOVERABLE_MOUSE_ENTER';
export const ON_HOVERABLE_MOUSE_LEAVE = 'ON_HOVERABLE_MOUSE_LEAVE';

export const SET_MODIFICATION = 'SET_MODIFICATION';
export const SET_SELECTED_MODIFICATION = 'SET_SELECTED_MODIFICATION';

export const SET_ZOOM_LEVEL = 'SET_ZOOM_LEVEL';
export const SET_SIDEBAR_OPEN = 'SET_SIDEBAR_OPEN';

export const SET_SHOW_PREVIEW = 'SET_SHOW_PREVIEW'