export const SET_SELECTED = 'SET_SELECTED';
export const SET_SHIFT_DOWN = 'SET_SHIFT_DOWN';
export const ON_HOVERABLE_MOUSE_ENTER = 'ON_HOVERABLE_MOUSE_ENTER';
export const ON_HOVERABLE_MOUSE_LEAVE = 'ON_HOVERABLE_MOUSE_LEAVE';

export const SET_MODIFICATIONS = 'SET_MODIFICATIONS';

export const SET_ZOOM_LEVEL = 'SET_ZOOM_LEVEL';